apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zhivko
  name: zhivko
spec:
  replicas: 10
  selector:
    matchLabels:
      app: zhivko
  template:
    metadata:
      labels:
        app: zhivko
    spec:
      containers:
        - image: httpd:alpine3.18
          name: httpd
  strategy:
    type: Recreate
